apiVersion: apps/v1
kind: Deployment
metadata:
  name: starai-web
  namespace: starai-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starai-web
  template:
    metadata:
      labels:
        app: starai-web
      annotations:
        conjur.org/container-mode: "sidecar"
        conjur.org/authenticator-id: "Arun-MIM"
    spec:
      serviceAccountName: starai-app-sa
      containers:
        - name: starai-web
          image: arunrana1214/starai:latest
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: conjur-connect
          volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
        - image: cyberark/conjur-authn-k8s-client
          imagePullPolicy: Always
          name: authenticator
          env:
            - name: JWT_TOKEN_PATH
              value: /var/run/secrets/tokens/jwt
            - name: LOG_LEVEL
              value: debug
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - mountPath: /run/conjur
              name: conjur-access-token
            - mountPath: /var/run/secrets/tokens
              name: jwt-token
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: https://kubernetes.default.svc
